wip: pipeline refactor

diff --git a/.devops/templates/liquibase-status.yml b/.devops/templates/liquibase-status.yml
--- a/.devops/templates/liquibase-status.yml
+++ b/.devops/templates/liquibase-status.yml
@@ -82,65 +82,60 @@ parameters:
     type: string
     default: "-"
 
-jobs:
-  - job: liquibase_status
-    displayName: Liquibase status ${{ parameters.DATABASE_NAME }}
-    strategy:
-      parallel: 1
+
+steps:
+  - script: |
+      if [ ! -f src/psql/nodo/liquibase/${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }}/db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml ]; then
+        echo "Version ${{ parameters.LIQUIBASE_DB_VERSION }} not defined for ${{ parameters.DATABASE_NAME }}"
+        echo "File db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml not found in folder ${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }}!"
+        exit 1
+      fi
+    displayName: "Check if Liquibase version exists"
+  - script: |
+        liquibase \
+        --url="${{ parameters.JDBC_URL }}" \
+        --username="${{ parameters.USERNAME }}" \
+        --password="${{ parameters.PASSWORD }}" \
+        --classpath=src/psql/nodo/liquibase/${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }} \
+        --changeLogFile=db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml \
+        ${{ if eq(parameters.LIQUIBASE_SCHEMA_NAME, '-') }}:
+          --liquibaseSchemaName="${{ parameters.SCHEMA }}" \
+        ${{ else }}:
+          --liquibaseSchemaName="${{ parameters.LIQUIBASE_SCHEMA_NAME }}" \
+        --defaultSchemaName="${{ parameters.SCHEMA }}" \
+        --contexts="${{ parameters.lbContexts }}" \
+        --log-level=${{ parameters.lbLogLevel }} \
+        ${{ if ne(parameters.CHANGELOG_LOCK_TABLE, '-') }}:
+          --database-changelog-lock-table-name="DATABASECHANGELOGLOCK_ADMIN" \
+        ${{ if ne(parameters.CHANGELOG_TABLE, '-') }}:
+          --database-changelog-table-name="DATABASECHANGELOG_ADMIN" \
+        status -Dschema=${{ parameters.SCHEMA }} -DschemaOffline=${{ parameters.OFFLINE_SCHEMA }} \
+        -DusernameOffline=${{ parameters.OFFLINE_USERNAME }} -DschemaOnline=${{ parameters.ONLINE_SCHEMA }} \
+        -Dnodo-db-host=${{ parameters.NODO_DB_HOST }} -Dnodo-db-port=${{ parameters.NODO_DB_PORT }} \
+        -Dpartition-password=${{ parameters.DB_PARTITION_PASSWORD }} -Dadmin-password=${{ parameters.DB_ADMIN_PASSWORD }}
+    displayName: "${{ parameters.DATABASE_NAME }} ${{ parameters.TARGET_DB_TYPE }} db status"
     condition: succeeded()
-    steps:
-      - script: |
-          if [ ! -f src/psql/nodo/liquibase/${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }}/db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml ]; then
-            echo "Version ${{ parameters.LIQUIBASE_DB_VERSION }} not defined for ${{ parameters.DATABASE_NAME }}"
-            echo "File db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml not found in folder ${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }}!"
-            exit 1
-          fi
-        displayName: "Check if Liquibase version exists"
-      - script: |
-            liquibase \
-            --url="${{ parameters.JDBC_URL }}" \
-            --username="${{ parameters.USERNAME }}" \
-            --password="${{ parameters.PASSWORD }}" \
-            --classpath=src/psql/nodo/liquibase/${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }} \
-            --changeLogFile=db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml \
-            ${{ if eq(parameters.LIQUIBASE_SCHEMA_NAME, '-') }}:
-              --liquibaseSchemaName="${{ parameters.SCHEMA }}" \
-            ${{ else }}:
-              --liquibaseSchemaName="${{ parameters.LIQUIBASE_SCHEMA_NAME }}" \
-            --defaultSchemaName="${{ parameters.SCHEMA }}" \
-            --contexts="${{ parameters.lbContexts }}" \
-            --log-level=${{ parameters.lbLogLevel }} \
-            ${{ if ne(parameters.CHANGELOG_LOCK_TABLE, '-') }}:
-              --database-changelog-lock-table-name="DATABASECHANGELOGLOCK_ADMIN" \
-            ${{ if ne(parameters.CHANGELOG_TABLE, '-') }}:
-              --database-changelog-table-name="DATABASECHANGELOG_ADMIN" \
-            status -Dschema=${{ parameters.SCHEMA }} -DschemaOffline=${{ parameters.OFFLINE_SCHEMA }} \
-            -DusernameOffline=${{ parameters.OFFLINE_USERNAME }} -DschemaOnline=${{ parameters.ONLINE_SCHEMA }} \
-            -Dnodo-db-host=${{ parameters.NODO_DB_HOST }} -Dnodo-db-port=${{ parameters.NODO_DB_PORT }} \
-            -Dpartition-password=${{ parameters.DB_PARTITION_PASSWORD }} -Dadmin-password=${{ parameters.DB_ADMIN_PASSWORD }}
-        displayName: "${{ parameters.DATABASE_NAME }} ${{ parameters.TARGET_DB_TYPE }} db status"
-        condition: succeeded()
-      - script: |
-          liquibase \
-          --url="${{ parameters.JDBC_URL }}" \
-          --username="${{ parameters.USERNAME }}" \
-          --password="${{ parameters.PASSWORD }}" \
-          --classpath=src/psql/nodo/liquibase/${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }} \
-          --changeLogFile=db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml \
-          ${{ if eq(parameters.LIQUIBASE_SCHEMA_NAME, '-') }}:
-              --liquibaseSchemaName="${{ parameters.SCHEMA }}" \
-          ${{ else }}:
-              --liquibaseSchemaName="${{ parameters.LIQUIBASE_SCHEMA_NAME }}" \
-          --defaultSchemaName="${{ parameters.SCHEMA }}" \
-          --contexts="${{ parameters.lbContexts }}" \
-          --log-level=${{ parameters.lbLogLevel }} \
-          ${{ if ne(parameters.CHANGELOG_LOCK_TABLE, '-') }}:
-            --database-changelog-lock-table-name="DATABASECHANGELOGLOCK_ADMIN" \
-          ${{ if ne(parameters.CHANGELOG_TABLE, '-') }}:
-            --database-changelog-table-name="DATABASECHANGELOG_ADMIN" \
-          validate -Dschema=${{ parameters.SCHEMA }} -DschemaOffline=${{ parameters.OFFLINE_SCHEMA }} \
-          -DusernameOffline=${{ parameters.OFFLINE_USERNAME }} -DschemaOnline=${{ parameters.ONLINE_SCHEMA }} \
-          -Dnodo-db-host=${{ parameters.NODO_DB_HOST }} -Dnodo-db-port=${{ parameters.NODO_DB_PORT }} \
-          -Dpartition-password=${{ parameters.DB_PARTITION_PASSWORD }} -Dadmin-password=${{ parameters.DB_ADMIN_PASSWORD }}
-        displayName: "${{ parameters.DATABASE_NAME }} ${{ parameters.TARGET_DB_TYPE }} db validate"
-        condition: succeeded()
+  - script: |
+      liquibase \
+      --url="${{ parameters.JDBC_URL }}" \
+      --username="${{ parameters.USERNAME }}" \
+      --password="${{ parameters.PASSWORD }}" \
+      --classpath=src/psql/nodo/liquibase/${{ parameters.LIQUIBASE_FOLDER }}/${{ parameters.DATABASE_NAME }} \
+      --changeLogFile=db.changelog-master-${{ parameters.LIQUIBASE_DB_VERSION }}.xml \
+      ${{ if eq(parameters.LIQUIBASE_SCHEMA_NAME, '-') }}:
+          --liquibaseSchemaName="${{ parameters.SCHEMA }}" \
+      ${{ else }}:
+          --liquibaseSchemaName="${{ parameters.LIQUIBASE_SCHEMA_NAME }}" \
+      --defaultSchemaName="${{ parameters.SCHEMA }}" \
+      --contexts="${{ parameters.lbContexts }}" \
+      --log-level=${{ parameters.lbLogLevel }} \
+      ${{ if ne(parameters.CHANGELOG_LOCK_TABLE, '-') }}:
+        --database-changelog-lock-table-name="DATABASECHANGELOGLOCK_ADMIN" \
+      ${{ if ne(parameters.CHANGELOG_TABLE, '-') }}:
+        --database-changelog-table-name="DATABASECHANGELOG_ADMIN" \
+      validate -Dschema=${{ parameters.SCHEMA }} -DschemaOffline=${{ parameters.OFFLINE_SCHEMA }} \
+      -DusernameOffline=${{ parameters.OFFLINE_USERNAME }} -DschemaOnline=${{ parameters.ONLINE_SCHEMA }} \
+      -Dnodo-db-host=${{ parameters.NODO_DB_HOST }} -Dnodo-db-port=${{ parameters.NODO_DB_PORT }} \
+      -Dpartition-password=${{ parameters.DB_PARTITION_PASSWORD }} -Dadmin-password=${{ parameters.DB_ADMIN_PASSWORD }}
+    displayName: "${{ parameters.DATABASE_NAME }} ${{ parameters.TARGET_DB_TYPE }} db validate"
+    condition: succeeded()
